server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
    #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hollewch/springcloud.git
          search-paths: /springcloud-common/springcloud-common-config/src/main/java/com/frame/ConfigurationList/ #gtihub下的路径