server:
  port: 8011

#开启降级feign.hystrix
feign:
  hystrix:
    enabled: true

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

spring:
  application:
    name: springcloud-consumer-uac