spring:
  profiles:
    active: dev


---
server:
  port: 8830

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-admin-8830  #修改eureka上默认描述信息

spring:
  profiles: dev
  application:
    name: springcloud-admin

#info配置
info:
  app.name: wch-springcloud
  company.name: blog.wchstudy.com

#向admin展示详细信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
---
server:
  port: 8830

#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-admin-8830  #修改eureka上默认描述信息

spring:
  profiles: test
  application:
    name: springcloud-admin

#info配置
info:
  app.name: wch-springcloud
  company.name: blog.wchstudy.com

#向admin展示详细信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS