spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
  application:
    name: springcloud-zuul

server:
  port: 9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-zuul-9527  #修改eureka上默认描述信息
    prefer-ip-address: true

#向admin展示详细信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

info:
  app.name: springcloud-demo
  company.name: blog.springcloud.com
zuul:
  routes:
    uac.serviceId: springcloud-consumer-uac
    uac.path: /uac/** #更改访问名为如上
    uac2.serviceId: springcloud-provider-uac
    uac2.path: /uac2/**
    oauth.serviceId: springcloud-common-oauth2.0
    oauth.path: /oauth/**
  ignored-services: "*"  #不能再用默认名字访问,隐藏全部
  sensitive-headers: Set-Cookie、Cookie、Host、Connection、Content-Length、Content-Encoding、Server、Transfer-Encoding、X-Application-Context、Authorization


---
spring:
  profiles: test
  application:
    name: springcloud-zuul

server:
  port: 9527

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-zuul-9527  #修改eureka上默认描述信息
    prefer-ip-address: true

#向admin展示详细信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

info:
  app.name: springcloud-demo
  company.name: blog.springcloud.com
zuul:
  routes:
    uac.serviceId: springcloud-consumer-uac
    uac.path: /uac/** #更改访问名为如上
    uac2.serviceId: springcloud-provider-uac
    uac2.path: /uac2/**
  ignored-services: "*"  #不能再用默认名字访问,隐藏全部