server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
    #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hollewch/springcloud-config.git
          search-paths: abc #gtihub下的路径